/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Base;

/**
 *
 * @author ADINDA DWI WIJAYANTI
 */
public class Buat_Akun extends javax.swing.JFrame {

    /**
     * Creates new form Buat_Akun
     */
    public Buat_Akun() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_input_NoHP = new javax.swing.JTextField();
        txt_input_email = new javax.swing.JTextField();
        btn_daftar = new javax.swing.JButton();
        txt_input_password = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_input_NoHP.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txt_input_NoHP.setBorder(null);
        txt_input_NoHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_input_NoHPActionPerformed(evt);
            }
        });
        getContentPane().add(txt_input_NoHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 510, 50));

        txt_input_email.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txt_input_email.setBorder(null);
        txt_input_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_input_emailActionPerformed(evt);
            }
        });
        getContentPane().add(txt_input_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 500, 50));

        btn_daftar.setBackground(new java.awt.Color(62, 130, 255));
        btn_daftar.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btn_daftar.setForeground(new java.awt.Color(255, 255, 255));
        btn_daftar.setText("Daftar");
        btn_daftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_daftarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 510, 410, 60));

        txt_input_password.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txt_input_password.setBorder(null);
        getContentPane().add(txt_input_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 500, 40));

        jButton2.setBackground(new java.awt.Color(0,0,0,0)
        );
        jButton2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 255));
        jButton2.setText("Masuk");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 600, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_componet_CareNity/Sig up Canva.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1269, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_input_NoHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_input_NoHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_input_NoHPActionPerformed

    private void txt_input_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_input_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_input_emailActionPerformed

    private void btn_daftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_daftarActionPerformed
        Home_user TambahAnak = new  Home_user ();
        TambahAnak.setVisible(true);
    }//GEN-LAST:event_btn_daftarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         sig_in_user Masuk = new  sig_in_user ();
         Masuk.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buat_Akun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buat_Akun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buat_Akun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buat_Akun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buat_Akun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_daftar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txt_input_NoHP;
    private javax.swing.JTextField txt_input_email;
    private javax.swing.JTextField txt_input_password;
    // End of variables declaration//GEN-END:variables
}
