/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Base;

/**
 *
 * @author ADINDA DWI WIJAYANTI
 */
public class Home_user extends javax.swing.JFrame {

    /**
     * Creates new form Home_user
     */
    public Home_user() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_TambahAnak = new javax.swing.JButton();
        btn_transaksi = new javax.swing.JButton();
        btn_chatdokter = new javax.swing.JButton();
        btn_komunitas = new javax.swing.JButton();
        btn_konten = new javax.swing.JButton();
        btn_home = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_TambahAnak.setBackground(new java.awt.Color(62, 130, 255));
        btn_TambahAnak.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        btn_TambahAnak.setForeground(new java.awt.Color(255, 255, 255));
        btn_TambahAnak.setText("+ Tambah Anak");
        btn_TambahAnak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TambahAnakActionPerformed(evt);
            }
        });
        getContentPane().add(btn_TambahAnak, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 390, 90));

        btn_transaksi.setText("Transaksi");
        btn_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksiActionPerformed(evt);
            }
        });
        getContentPane().add(btn_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 290, 120, -1));

        btn_chatdokter.setText("Chat Dokter");
        getContentPane().add(btn_chatdokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 370, 120, -1));

        btn_komunitas.setText("Komunitas");
        getContentPane().add(btn_komunitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 470, 120, -1));

        btn_konten.setText("Konten");
        getContentPane().add(btn_konten, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 550, 100, -1));

        btn_home.setForeground(new java.awt.Color(62, 130, 255));
        btn_home.setText("Home");
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 120, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_componet_CareNity/Home User.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TambahAnakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TambahAnakActionPerformed
        profil_anak Lanjutkedataortu  = new  profil_anak ();
        Lanjutkedataortu.setVisible(true);
    }//GEN-LAST:event_btn_TambahAnakActionPerformed

    private void btn_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_transaksiActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        Home_user home = new Home_user();
        home.setVisible(true);
    }//GEN-LAST:event_btn_homeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_TambahAnak;
    private javax.swing.JButton btn_chatdokter;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_komunitas;
    private javax.swing.JButton btn_konten;
    private javax.swing.JButton btn_transaksi;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
