/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Base;

/**
 *
 * @author ADINDA DWI WIJAYANTI
 */
public class profil_MomandDad extends javax.swing.JFrame {

    /**
     * Creates new form profil_MomandDad
     */
    public profil_MomandDad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_input_TinggiBadanMom = new javax.swing.JTextField();
        txt_input_BBMom = new javax.swing.JTextField();
        txt_input_UmurMom = new javax.swing.JTextField();
        txt_input_BBDad = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        txt_input_UmurDad = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        btn_home = new javax.swing.JButton();
        btn_transaksi = new javax.swing.JButton();
        btn_chatdokter = new javax.swing.JButton();
        btn_komunitas = new javax.swing.JButton();
        btn_konten = new javax.swing.JButton();
        txt_input_tinggiBadanDad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_input_TinggiBadanMom.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        txt_input_TinggiBadanMom.setBorder(null);
        txt_input_TinggiBadanMom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_input_TinggiBadanMomActionPerformed(evt);
            }
        });
        getContentPane().add(txt_input_TinggiBadanMom, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 216, 510, 20));

        txt_input_BBMom.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        txt_input_BBMom.setBorder(null);
        txt_input_BBMom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_input_BBMomActionPerformed(evt);
            }
        });
        getContentPane().add(txt_input_BBMom, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 284, 510, -1));

        txt_input_UmurMom.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        txt_input_UmurMom.setBorder(null);
        getContentPane().add(txt_input_UmurMom, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 510, -1));

        txt_input_BBDad.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        txt_input_BBDad.setBorder(null);
        getContentPane().add(txt_input_BBDad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 510, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jTextField1.setBorder(null);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 510, 20));

        txt_input_UmurDad.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        txt_input_UmurDad.setBorder(null);
        getContentPane().add(txt_input_UmurDad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 580, 510, -1));

        btn_simpan.setBackground(new java.awt.Color(62, 130, 255));
        btn_simpan.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        btn_simpan.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 520, 310, 70));

        btn_home.setForeground(new java.awt.Color(62, 130, 255));
        btn_home.setText("Home");
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 90, 30));

        btn_transaksi.setText("Transaksi");
        getContentPane().add(btn_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 280, 100, -1));

        btn_chatdokter.setText("Chat Dokter");
        getContentPane().add(btn_chatdokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 120, -1));

        btn_komunitas.setText("Komunitas");
        getContentPane().add(btn_komunitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 110, -1));

        btn_konten.setText("Konten");
        getContentPane().add(btn_konten, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 90, -1));

        txt_input_tinggiBadanDad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_componet_CareNity/profil mom and dad.png"))); // NOI18N
        getContentPane().add(txt_input_tinggiBadanDad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_input_TinggiBadanMomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_input_TinggiBadanMomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_input_TinggiBadanMomActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        Home Berhasil = new Home();
        Berhasil.setVisible(true);
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        Home_user Kembali = new Home_user();
        Kembali.setVisible(true);
    }//GEN-LAST:event_btn_homeActionPerformed

    private void txt_input_BBMomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_input_BBMomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_input_BBMomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profil_MomandDad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profil_MomandDad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profil_MomandDad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profil_MomandDad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profil_MomandDad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_chatdokter;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_komunitas;
    private javax.swing.JButton btn_konten;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_transaksi;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txt_input_BBDad;
    private javax.swing.JTextField txt_input_BBMom;
    private javax.swing.JTextField txt_input_TinggiBadanMom;
    private javax.swing.JTextField txt_input_UmurDad;
    private javax.swing.JTextField txt_input_UmurMom;
    private javax.swing.JLabel txt_input_tinggiBadanDad;
    // End of variables declaration//GEN-END:variables
}
