/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Base;

/**
 *
 * @author ADINDA DWI WIJAYANTI
 */
public class profil_anak extends javax.swing.JFrame {

    /**
     * Creates new form profil_anak
     */
    public profil_anak() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        txt_input_namaAnak = new javax.swing.JTextField();
        txt_inpput_tglLahir = new javax.swing.JTextField();
        btn_lanjutkeDataOrtu = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButton1.setBackground(new java.awt.Color(0,0,0,0)
        );
        jRadioButton1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jRadioButton1.setText("Perempuan");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 461, 140, 40));

        jRadioButton2.setBackground(new java.awt.Color(0,0,0,0)
        );
        jRadioButton2.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jRadioButton2.setText("Laki-laki");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, 120, 40));

        jRadioButton3.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jRadioButton3.setText("Ya");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, 80, 40));

        jRadioButton4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jRadioButton4.setText("Tidak");
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, 100, 40));

        txt_input_namaAnak.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txt_input_namaAnak.setBorder(null);
        getContentPane().add(txt_input_namaAnak, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 510, 30));

        txt_inpput_tglLahir.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txt_inpput_tglLahir.setBorder(null);
        getContentPane().add(txt_inpput_tglLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 510, 30));

        btn_lanjutkeDataOrtu.setBackground(new java.awt.Color(255, 255, 255));
        btn_lanjutkeDataOrtu.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn_lanjutkeDataOrtu.setForeground(new java.awt.Color(57, 53, 255));
        btn_lanjutkeDataOrtu.setText("Lanjut Ke Data Ortu");
        btn_lanjutkeDataOrtu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lanjutkeDataOrtuActionPerformed(evt);
            }
        });
        getContentPane().add(btn_lanjutkeDataOrtu, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 100, 250, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_componet_CareNity/profil anak.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void btn_lanjutkeDataOrtuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lanjutkeDataOrtuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_lanjutkeDataOrtuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profil_anak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profil_anak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profil_anak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profil_anak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profil_anak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_lanjutkeDataOrtu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField txt_inpput_tglLahir;
    private javax.swing.JTextField txt_input_namaAnak;
    // End of variables declaration//GEN-END:variables
}
