/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Base;

/**
 *
 * @author ADINDA DWI WIJAYANTI
 */
public class profil_anak extends javax.swing.JFrame {

    /**
     * Creates new form profil_anak
     */
    public profil_anak() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbt_perempuan = new javax.swing.JRadioButton();
        rbt_lakilaki = new javax.swing.JRadioButton();
        rbt_ya = new javax.swing.JRadioButton();
        rbt_tidak = new javax.swing.JRadioButton();
        txt_input_namaAnak = new javax.swing.JTextField();
        txt_inpput_tglLahir = new javax.swing.JTextField();
        btn_home = new javax.swing.JButton();
        btn_transaksi = new javax.swing.JButton();
        btn_chatdokter = new javax.swing.JButton();
        btn_komunitas = new javax.swing.JButton();
        btn_konten = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbt_perempuan.setBackground(new java.awt.Color(0,0,0,0)
        );
        rbt_perempuan.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        rbt_perempuan.setText("Perempuan");
        getContentPane().add(rbt_perempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 461, 140, 40));

        rbt_lakilaki.setBackground(new java.awt.Color(0,0,0,0)
        );
        rbt_lakilaki.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        rbt_lakilaki.setText("Laki-laki");
        getContentPane().add(rbt_lakilaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, 120, 40));

        rbt_ya.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        rbt_ya.setText("Ya");
        rbt_ya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_yaActionPerformed(evt);
            }
        });
        getContentPane().add(rbt_ya, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, 80, 40));

        rbt_tidak.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rbt_tidak.setText("Tidak");
        getContentPane().add(rbt_tidak, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, 100, 40));

        txt_input_namaAnak.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txt_input_namaAnak.setBorder(null);
        getContentPane().add(txt_input_namaAnak, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 510, 30));

        txt_inpput_tglLahir.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txt_inpput_tglLahir.setBorder(null);
        getContentPane().add(txt_inpput_tglLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 510, 30));

        btn_home.setForeground(new java.awt.Color(62, 130, 255));
        btn_home.setText("Home");
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 120, -1));

        btn_transaksi.setText("Transaksi");
        getContentPane().add(btn_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 120, -1));

        btn_chatdokter.setText("Chat Dokter");
        getContentPane().add(btn_chatdokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 350, 120, -1));

        btn_komunitas.setText("Komunitas");
        getContentPane().add(btn_komunitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 120, -1));

        btn_konten.setText("Konten");
        getContentPane().add(btn_konten, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 100, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(57, 35, 255));
        jButton1.setText("Lanjut Ke Data Ortu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 80, 320, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_componet_CareNity/profil anak.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbt_yaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_yaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_yaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        profil_MomandDad Simpan = new profil_MomandDad ();
        Simpan.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        Home_user Kembali = new Home_user();
        Kembali.setVisible(true);
    }//GEN-LAST:event_btn_homeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profil_anak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profil_anak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profil_anak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profil_anak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profil_anak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_chatdokter;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_komunitas;
    private javax.swing.JButton btn_konten;
    private javax.swing.JButton btn_transaksi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rbt_lakilaki;
    private javax.swing.JRadioButton rbt_perempuan;
    private javax.swing.JRadioButton rbt_tidak;
    private javax.swing.JRadioButton rbt_ya;
    private javax.swing.JTextField txt_inpput_tglLahir;
    private javax.swing.JTextField txt_input_namaAnak;
    // End of variables declaration//GEN-END:variables
}
