/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Base;

/**
 *
 * @author ADINDA DWI WIJAYANTI
 */
public class sig_in_user extends javax.swing.JFrame {

    /**
     * Creates new form sig_in_user
     */
    public sig_in_user() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_input_NoHp = new javax.swing.JTextField();
        btn_Masuk = new javax.swing.JButton();
        btn_password = new javax.swing.JButton();
        psw_password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_input_NoHp.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        txt_input_NoHp.setBorder(null);
        getContentPane().add(txt_input_NoHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 510, 50));

        btn_Masuk.setBackground(new java.awt.Color(62, 130, 255));
        btn_Masuk.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btn_Masuk.setText("Masuk");
        btn_Masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MasukActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 490, 370, 80));

        btn_password.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_password.setForeground(new java.awt.Color(0, 0, 255));
        btn_password.setText("Password Baru");
        btn_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(btn_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 580, 190, 40));

        psw_password.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        psw_password.setBorder(null);
        getContentPane().add(psw_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 230, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_componet_CareNity/Sig in.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MasukActionPerformed
        Home_user Berhasil = new Home_user();
        Berhasil.setVisible(true);
    }//GEN-LAST:event_btn_MasukActionPerformed

    private void btn_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_passwordActionPerformed
        Lupa_Password Simpan = new Lupa_Password ();
        Simpan.setVisible(true);
    }//GEN-LAST:event_btn_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sig_in_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sig_in_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sig_in_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sig_in_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sig_in_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Masuk;
    private javax.swing.JButton btn_password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField psw_password;
    private javax.swing.JTextField txt_input_NoHp;
    // End of variables declaration//GEN-END:variables
}
