/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Base;

/**
 *
 * @author ADINDA DWI WIJAYANTI
 */
public class Update_Pertumbuhan extends javax.swing.JFrame {

    /**
     * Creates new form Update_Pertumbuhan
     */
    public Update_Pertumbuhan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_tglPertumbuhan = new javax.swing.JTextField();
        txt_TinggiBadan = new javax.swing.JTextField();
        txt_BeratBadan = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        txt_LingkarKepala = new javax.swing.JTextField();
        btn_Simpan = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        txt_UsiaAnak = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_tglPertumbuhan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_tglPertumbuhan.setBorder(null);
        getContentPane().add(txt_tglPertumbuhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 470, 30));

        txt_TinggiBadan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_TinggiBadan.setBorder(null);
        getContentPane().add(txt_TinggiBadan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 470, 30));

        txt_BeratBadan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_BeratBadan.setBorder(null);
        getContentPane().add(txt_BeratBadan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 470, 30));

        jButton1.setText("+ Unggah Foto");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, 310, 70));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField1.setBorder(null);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, 390, -1));

        txt_LingkarKepala.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_LingkarKepala.setBorder(null);
        getContentPane().add(txt_LingkarKepala, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, 390, -1));

        btn_Simpan.setBackground(new java.awt.Color(62, 130, 255));
        btn_Simpan.setFont(new java.awt.Font("Segoe UI Semibold", 2, 36)); // NOI18N
        btn_Simpan.setForeground(new java.awt.Color(255, 255, 255));
        btn_Simpan.setText("Simpan");
        btn_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, 320, 70));

        btn_back.setBackground(new java.awt.Color(0,0,0,0)
        );
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, 90));

        txt_UsiaAnak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_componet_CareNity/Update Pertumbuhan.png"))); // NOI18N
        getContentPane().add(txt_UsiaAnak, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SimpanActionPerformed
        Data_Anak Kembali = new Data_Anak();
        Kembali.setVisible(true);
    }//GEN-LAST:event_btn_SimpanActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        Data_Anak dataanak = new Data_Anak();
        dataanak.setVisible(true);
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_Pertumbuhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_Pertumbuhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_Pertumbuhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_Pertumbuhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_Pertumbuhan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Simpan;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txt_BeratBadan;
    private javax.swing.JTextField txt_LingkarKepala;
    private javax.swing.JTextField txt_TinggiBadan;
    private javax.swing.JLabel txt_UsiaAnak;
    private javax.swing.JTextField txt_tglPertumbuhan;
    // End of variables declaration//GEN-END:variables
}
